(* Exception types have to be defined before they can be thrown or caught. *)
(exception Serious_error)

(val get_value (bool) -> string)
(let get_value (x) (if x "a value" (throw Serious_error)))

(val main () -> i64)
(let main () {
    (print (.. "got " (try (get_value true) (
        (catch Serious_error "serious error")))))
    (print (.. "got " (try (get_value false) (
        (catch Serious_error "serious error")))))
    0
})
